src/mentorpal/metrics.py
Better logging for checkpoint test (display first few words of answer instead of an id)
Use answer text instead of answer id
=> Test metrics

services/web-app/public/home.js, services/web-app/public/index.js, services/web-app/views/home.html, services/web-app/views/index.html
On mobile devices, hide the nav header
Home screen supports mobile device widths
=> Embed mobile

mentors/carlos/data/topics.csv, mentors/clint/data/topics.csv, mentors/dan/data/topics.csv, mentors/julianne/data/topics.csv, services/web-app/public/index.js
Selecting a topic button will get a random question from a random topic in that over-arching topic.
=> Topic buttons now list a small set of over-arching topics.

client/MentorPanel/src/api/api.js, client/MentorPanel/src/components/header.js, client/MentorPanel/src/components/input.js, client/MentorPanel/src/components/video-panel.js, client/MentorPanel/src/components/video-thumbnail.js, client/MentorPanel/src/components/video.js, client/MentorPanel/src/pages/index.js, client/MentorPanel/src/redux/actions.js, client/MentorPanel/src/redux/reducer.js, client/MentorPanel/src/styles/layout.css, client/MentorPanel/yarn.lock
After sending a question to mentor panel, show loading spinner over panel members while they load
Fixing issue where idle would not play
=> loading spinner

client/MentorPanel/src/api/api.js, client/MentorPanel/src/components/input.js, client/MentorPanel/src/components/video-panel.js, client/MentorPanel/src/components/video-thumbnail.js, client/MentorPanel/src/components/video.js, client/MentorPanel/src/pages/index.js, client/MentorPanel/src/redux/actions.js, client/MentorPanel/src/redux/store.js, client/MentorPanel/src/styles/layout.css, client/MentorPanel/wrap-with-provider.js
Hitting enter inside textfield sends the input
Video centered with set width
Fave icon appears in corner of video
=> some ui fixes

client/MentorPanel/src/components/input.js, client/MentorPanel/src/components/video.js
Show last question asked as hint text in inputfield
=> Don't show subtitles over idle video

src/mentorpal/classifiers/arch/lstm_v2/__init__.py, src/mentorpal/classifiers/arch/lstm_v2/training/__init__.py
Adjusted training data to fix mismatch between training and testing data
=> Feature mismatch fix

.circleci/config.yml, services/mentor-api/Makefile
* gives PRs option to deploy to dev-mentorpal
=> Update config.yml (#2)

Makefile
- fixes `make docker-build-services` from root
=> fix makefile error

client/MentorPanel/package-lock.json, client/MentorPanel/package.json, client/MentorPanel/src/components/header.js, client/MentorPanel/src/components/questions.js, client/MentorPanel/src/components/scrolling_questions.js, client/MentorPanel/src/components/topics.js, client/MentorPanel/src/components/video-panel.js, client/MentorPanel/src/pages/index.js, client/MentorPanel/src/redux/actions.js, client/MentorPanel/src/wrap-with-location.js
Recommended topic contains recommended questions
Recommended topic appears first if there is one
First topic is selected but input field is empty when entering app
Don't crash when all questions in a topic have been asked
If a recommended question is in another topic, put it at the top
Denote recommended questions with a * (temporarily)
=> Can pass array of recommended questions in query parameters

client/MentorPanel/src/components/input.js, client/MentorPanel/src/components/questions.js, client/MentorPanel/src/components/scrolling_questions.js, client/MentorPanel/src/components/topics.js, client/MentorPanel/src/components/video-panel.js, client/MentorPanel/src/components/video-thumbnail.js, client/MentorPanel/src/components/video.js, client/MentorPanel/src/pages/index.js, client/MentorPanel/src/styles/layout.css
Fix bug where questions list was too tall and slightly off screen on first launch
Make screen unscrollable outside scrolling elements
=> Make video and input area both take 50% of screen

client/MentorPanel/src/api/api.js, client/MentorPanel/src/components/video-thumbnail.js, client/MentorPanel/src/components/video.js, client/MentorPanel/src/pages/index.js, client/MentorPanel/src/styles/layout.css
Scrolling for topics and questions is kinetic
Window resize listener
If header is longer than screen width, don't wrap and use ellipses instead
=> Use either mobile or web video size based on phone size

client/MentorPanel/package-lock.json, client/MentorPanel/src/components/input.js, client/MentorPanel/src/components/scrolling_questions.js, client/MentorPanel/src/components/topics.js, client/MentorPanel/src/components/video.js, client/MentorPanel/src/redux/actions.js, client/MentorPanel/src/redux/store.js
History displays list of asked questions
History topic button has history icon
Recommended topic button has recommended icon
Recommended questions now use recommended icon
Adding top shadow to input field area
=> Adding history topic button

client/MentorPanel/src/components/input.js, client/MentorPanel/src/components/questions.js, client/MentorPanel/src/components/scrolling_questions.js, client/MentorPanel/src/components/video-panel.js, client/MentorPanel/src/components/video-spinner.js, client/MentorPanel/src/components/video-status.js, client/MentorPanel/src/components/video-thumbnail.js, client/MentorPanel/src/components/video.js, client/MentorPanel/src/pages/index.js, client/MentorPanel/src/redux/actions.js, client/MentorPanel/src/styles/layout.css
If on desktop, use better desktop layout UI
Query param for page with a single mentor
Don't sort recommended questions to top of history question list
Add load/status icons to main video area
=> MentorPal single mentor and Desktop layout

mentors/Makefile, mentors/src/data_pipeline/post_process_data.py
- Fix hardcoded number of paraphrases in code
- Fix build, by preventing removal of intermediate build files when running data/update
=> Fix pipeline bugs

mentors/src/data_pipeline/transcript_adapter.py
- adds column defs to pandas data frames
so they can be accessed by column name even when empty
- fixes logic error about printing warning on empty data frames(was AND but should be OR)
=> fixes fail on no utterance data

classifier/requirements.txt
Need this to enable pytest unit testing in virtualenv for mentor-api, but not a bad idea to update anyway
=> updates classifier tensorflow and numpy versions

.circleci/config.yml, .gitignore, classifier/Makefile, classifier/requirements.test.txt, classifier/src/mentorpal/mentor.py, classifier/tests/resources/mentors/mentor_01/data/classifier_data.csv, classifier/tests/resources/mentors/mentor_01/data/profile.yml, classifier/tests/resources/mentors/mentor_01/data/topics.csv, classifier/tests/resources/mentors/mentor_01/data/utterance_data.csv, classifier/tests/test_mentor.py
Enables pytest for classifier with 1 very basic initial/placeholder test
=> Enables pytest for classifier

.circleci/config.yml
- caches/reuses revision checkout for most test steps
=> optimizes CI build times by caching git clones (by revision)

.gitignore, classifier/.coveragerc, classifier/pytest.ini, classifier/requirements.test.txt, mentors/.coveragerc, mentors/pytest.ini, mentors/requirements.test.txt, services/mentor-api/.coveragerc, services/mentor-api/pytest.ini, services/mentor-api/tests/requirements.txt
added test-coverage reports for WIP on mentor pipeline, but better to pull it out as it's own PR
=> adds test-coverage reports

docker-compose.dev-override.yml, docker-compose.yml
this can only be fully tested if you have local videos, but the idea is that when you do
`make local-run-dev`
...and then open the web app at `localhost: 8080`, it will be pulling videos also from `localhost:8080/videos`
=> fixes running local with local videos

checkpoint/Makefile, checkpoint/README.md
make checkpoint-train-XXX tries to ensure vector models etc. have been pulled from git lfs
=> make checkpoint-train-XXX and git lfs

mentors/data/mentors/dan-burns/data/profile.yml, mentors/data/mentors/jd_thomas/data/profile.yml, mentors/data/mentors/mario-pais/data/profile.yml
In accordance with this ticket:
https://app.asana.com/0/1156473794591610/1156475748668728
View updated mentors here on dev:
https://dev.mentorpal.org/mentorpanel/?mentor=jd_thomas&mentor=mario-pais&mentor=dan-burns
=> corrects titles for leadership mentors
